import randomItem from "@utils/randomItem.ts";

const adjectives: string[] = [
  "Wobbly",
  "Fickle",
  "Zigzagging",
  "Whimsical",
  "Bouncy",
  "Jolly",
  "Giddy",
  "Sprightly",
  "Merry",
  "Lighthearted",
  "Silly",
  "Cheerful",
  "Animated",
  "Goofy",
  "Playful",
  "Wacky",
  "Joyful",
  "Eccentric",
  "Quirky",
  "Flamboyant",
  "Dizzy",
  "Zany",
  "Surreal",
  "Jovial",
  "Lively",
  "Hilarious",
  "Crazy",
  "Frolicsome",
  "Euphoric",
  "Mischievous",
];

const nouns: string[] = [
  "Pogo Stick",
  "Unicycle",
  "Penny Farthing",
  "Scooter",
  "Velocipede",
  "Hoverboard",
  "Skateboard",
  "Tuk-tuk",
  "Hot Air Balloon",
  "Tricycle",
  "Bumper Car",
  "Roller Skates",
  "Shopping Cart",
  "Golf Cart",
  "Sleigh",
  "Sardine Can",
  "Bubble Wrap",
  "Rubber Chicken",
  "Feather Duster",
  "Giant Banana",
  "Circus Cannon",
  "Inflatable Flamingo",
  "Whoopee Cushion",
  "Silly String",
  "Flying Saucer",
  "Glow Stick",
  "Palm Tree Float",
  "Gummy Worm",
  "Party Hat",
  "Disco Ball",
];

export default function randomName(): string {
  return `${randomItem(adjectives)} ${randomItem(nouns)}`;
}
